name: umovieapp
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <=4.0.0"

dependencies:
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  firebase_analytics: ^10.10.5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  get_it: ^7.1.3
  google_fonts: ^6.2.1
  gson: ^0.1.4
  http: ^1.1.0
  path_provider: ^2.0.2
  provider: ^6.0.3
  sqflite: ^2.0.0+3

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/
